project_id = "dxzxuvshztvnizzevnye"

[functions.seed-admin]
verify_jwt = false

[functions.seed-data]
verify_jwt = false

[functions.seed-finance]
verify_jwt = false

[functions.admin-create-professor-user]
verify_jwt = false
